### ISSUE TITLE
Modify Page Header?

### ISSUE THREAD

**Issue by SeanMeyer** [hswick/jutsu#6]
This library is fantastic, but I'm wondering if it's necessary to have the Jutsu header on the page without any ability to change it. I'm working on a project where that would feel very out of place and was hoping for a way to change the page header. Would you be open to making the header an option that can be changed?

**Comment by hswick** [comment]
Hi! Glad you like it. Was gonna keep that till someone complained about it. So here we are :D

I️ was hoping to make it configurable so users could display different options. And the infrastructure to make it happen is in place. 

If it’s urgent for you feel to make a PR otherwise I’ll change it when I️ get around to it

**Comment by SeanMeyer** [comment]
I'll look into making a PR soon, as I have been loving Jutsu and would like to contribute. I'm still pretty inexperienced at Clojure though, so it might take me some time. Thanks for this library btw!

**Comment by hswick** [comment]
you can now use (graph!
